/**
 * Generates src/format/entry-view/tool-view/generated.ts from the captured
 * tool-schemas.json (see capture.ts): one input interface per tool via
 * json-schema-to-typescript, the ToolName union, TOOL_NAMES, and
 * ToolInputMap. Output is formatted with the repo's prettier so treefmt is a
 * no-op on it.
 *
 * Entry point: node scripts/claude-tools/generate.ts [--check]
 *
 * `--check` (presubmit) regenerates in memory and fails on any diff against
 * the checked-in file, and fails if tool-schemas.json was captured from a
 * different claude than the bundled one (recorded sdkVersion vs the
 * installed @anthropic-ai/claude-agent-sdk version — a local file read, no
 * network) — so an SDK bump turns presubmit red until capture.ts is rerun.
 */

import { readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { compile } from "json-schema-to-typescript";
import prettier from "prettier";
import type { ToolSchemas } from "./capture.ts";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(scriptDir, "..", "..");
const toolSchemasPath = join(scriptDir, "tool-schemas.json");
const generatedPath = join(
  repoRoot,
  "src",
  "format",
  "entry-view",
  "tool-view",
  "generated.ts",
);

async function generate(schemas: ToolSchemas): Promise<string> {
  const names = schemas.tools.map((tool) => tool.name);
  const interfaces = await Promise.all(
    schemas.tools.map((tool) =>
      compile(tool.input_schema, `${tool.name}Input`, {
        bannerComment: "",
        format: false,
        additionalProperties: false,
      }),
    ),
  );
  const source = [
    "// GENERATED FILE — do not edit.",
    `// Input types for the tools of claude ${schemas.claudeVersion} (sdk ${schemas.sdkVersion}),`,
    "// generated by scripts/claude-tools/generate.ts from tool-schemas.json.",
    "// To refresh after an SDK bump: node scripts/claude-tools/capture.ts",
    "",
    "// Some tools genuinely take no input (e.g. TaskList).",
    "/* eslint-disable @typescript-eslint/no-empty-object-type */",
    "",
    ...interfaces,
    `export type ToolName = ${names.map((name) => JSON.stringify(name)).join(" | ")};`,
    "",
    `export const TOOL_NAMES: readonly ToolName[] = [${names.map((name) => JSON.stringify(name)).join(", ")}];`,
    "",
    "export interface ToolInputMap {",
    ...names.map((name) => `  ${name}: ${name}Input;`),
    "}",
    "",
  ].join("\n");
  const config = await prettier.resolveConfig(generatedPath);
  return prettier.format(source, { ...config, filepath: generatedPath });
}

async function installedSdkVersion(): Promise<string> {
  const packageJson = JSON.parse(
    await readFile(
      join(
        repoRoot,
        "node_modules",
        "@anthropic-ai",
        "claude-agent-sdk",
        "package.json",
      ),
      "utf8",
    ),
  ) as { version: string };
  return packageJson.version;
}

/** Regenerate generated.ts from the checked-in tool-schemas.json; called by
 *  capture.ts after a capture so one command leaves both files consistent. */
export async function regenerate(): Promise<void> {
  const schemas = JSON.parse(
    await readFile(toolSchemasPath, "utf8"),
  ) as ToolSchemas;
  await writeFile(generatedPath, await generate(schemas));
  console.log(`wrote ${generatedPath} (${schemas.tools.length} tools)`);
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check");
  if (!check) {
    await regenerate();
    return;
  }
  const schemas = JSON.parse(
    await readFile(toolSchemasPath, "utf8"),
  ) as ToolSchemas;
  const generated = await generate(schemas);
  const installed = await installedSdkVersion();
  if (schemas.sdkVersion !== installed) {
    throw new Error(
      `tool-schemas.json was captured from sdk ${schemas.sdkVersion} but ` +
        `${installed} is installed — rerun scripts/claude-tools/capture.ts`,
    );
  }
  const onDisk = await readFile(generatedPath, "utf8");
  if (onDisk !== generated) {
    throw new Error(
      `${generatedPath} is stale — rerun scripts/claude-tools/generate.ts`,
    );
  }
  console.log("generated.ts is up to date");
}

if (process.argv[1] !== undefined) {
  if (import.meta.url === pathToFileURL(process.argv[1]).href) {
    main().catch((error: unknown) => {
      console.error(error instanceof Error ? error.message : error);
      process.exitCode = 1;
    });
  }
}
