// GENERATED FILE — do not edit.
// Input types for the tools of claude 2.1.211 (sdk 0.3.211),
// generated by scripts/claude-tools/generate.ts from tool-schemas.json.
// To refresh after an SDK bump: node scripts/claude-tools/capture.ts &&
// node scripts/claude-tools/generate.ts

// Some tools genuinely take no input (e.g. TaskList).
/* eslint-disable @typescript-eslint/no-empty-object-type */

export interface AgentInput {
  /**
   * A short (3-5 word) description of the task
   */
  description: string;
  /**
   * The task for the agent to perform
   */
  prompt: string;
  /**
   * The type of specialized agent to use for this task
   */
  subagent_type?: string;
  /**
   * Optional model override for this agent. Takes precedence over the agent definition's model frontmatter. If omitted, uses the agent definition's model, or inherits from the parent. Ignored for subagent_type: "fork" — forks always inherit the parent model.
   */
  model?: "sonnet" | "opus" | "haiku" | "fable";
  /**
   * Agents run in the background by default; you will be notified when one completes. Set to false to run this agent synchronously when you need its result before continuing.
   */
  run_in_background?: boolean;
  /**
   * Isolation mode. "worktree" creates a temporary git worktree so the agent works on an isolated copy of the repo. "remote" launches the agent in a remote cloud environment (always runs in background; availability is gated).
   */
  isolation?: "worktree" | "remote";
}

export interface BashInput {
  /**
   * The command to execute
   */
  command: string;
  /**
   * Optional timeout in milliseconds (max 600000)
   */
  timeout?: number;
  /**
   * Clear, concise description of what this command does in active voice. Never use words like "complex" or "risk" in the description - just describe what it does.
   *
   * For simple commands (git, npm, standard CLI tools), keep it brief (5-10 words):
   * - ls → "List files in current directory"
   * - git status → "Show working tree status"
   * - npm install → "Install package dependencies"
   *
   * For commands that are harder to parse at a glance (piped commands, obscure flags, etc.), add enough context to clarify what it does:
   * - find . -name "*.tmp" -exec rm {} \; → "Find and delete all .tmp files recursively"
   * - git reset --hard origin/main → "Discard all local changes and match remote main"
   * - curl -s url | jq '.data[]' → "Fetch JSON from URL and extract data array elements"
   */
  description?: string;
  /**
   * Set to true to run this command in the background.
   */
  run_in_background?: boolean;
  /**
   * Set this to true to dangerously override sandbox mode and run commands without sandboxing.
   */
  dangerouslyDisableSandbox?: boolean;
}

export interface CronCreateInput {
  /**
   * Standard 5-field cron expression in local time: "M H DoM Mon DoW" (e.g. "* /5 * * * *" = every 5 minutes, "30 14 28 2 *" = Feb 28 at 2:30pm local once).
   */
  cron: string;
  /**
   * The prompt to enqueue at each fire time.
   */
  prompt: string;
  /**
   * true (default) = fire on every cron match until deleted or auto-expired after 7 days. false = fire once at the next match, then auto-delete. Use false for "remind me at X" one-shot requests with pinned minute/hour/dom/month.
   */
  recurring?: boolean;
  /**
   * true = persist to .claude/scheduled_tasks.json and survive restarts. false (default) = in-memory only, dies when this Claude session ends. Use true only when the user asks the task to survive across sessions.
   */
  durable?: boolean;
}

export interface CronDeleteInput {
  /**
   * Job ID returned by CronCreate.
   */
  id: string;
}

export interface CronListInput {}

export interface DeferredToolPlaceholderInput {}

export interface EditInput {
  /**
   * The absolute path to the file to modify
   */
  file_path: string;
  /**
   * The text to replace
   */
  old_string: string;
  /**
   * The text to replace it with (must be different from old_string)
   */
  new_string: string;
  /**
   * Replace all occurrences of old_string (default false)
   */
  replace_all?: boolean;
}

export interface EnterWorktreeInput {
  /**
   * Optional name for a new worktree. Each "/"-separated segment may contain only letters, digits, dots, underscores, and dashes; max 64 chars total. A random name is generated if not provided. Mutually exclusive with `path`.
   */
  name?: string;
  /**
   * Path to an existing worktree to switch into instead of creating a new one. Must appear in `git worktree list` for the current repo — or, on first entry from the launch directory, for a repo nested inside it (multi-repo workspace). Mutually exclusive with `name`.
   */
  path?: string;
}

export interface ExitWorktreeInput {
  /**
   * "keep" leaves the worktree and branch on disk; "remove" deletes both.
   */
  action: "keep" | "remove";
  /**
   * Required true when action is "remove" and the worktree has uncommitted files or unmerged commits. The tool will refuse and list them otherwise.
   */
  discard_changes?: boolean;
}

export interface NotebookEditInput {
  /**
   * The absolute path to the Jupyter notebook file to edit (must be absolute, not relative)
   */
  notebook_path: string;
  /**
   * The ID of the cell to edit. When inserting a new cell, the new cell will be inserted after the cell with this ID, or at the beginning if not specified.
   */
  cell_id?: string;
  /**
   * The new source for the cell
   */
  new_source: string;
  /**
   * The type of the cell (code or markdown). If not specified, it defaults to the current cell type. If using edit_mode=insert, this is required.
   */
  cell_type?: "code" | "markdown";
  /**
   * The type of edit to make (replace, insert, delete). Defaults to replace.
   */
  edit_mode?: "replace" | "insert" | "delete";
}

export interface ReadInput {
  /**
   * The absolute path to the file to read
   */
  file_path: string;
  /**
   * The line number to start reading from. Only provide if the file is too large to read at once
   */
  offset?: number;
  /**
   * The number of lines to read. Only provide if the file is too large to read at once.
   */
  limit?: number;
  /**
   * Page range for PDF files (e.g., "1-5", "3", "10-20"). Only applicable to PDF files. Maximum 20 pages per request.
   */
  pages?: string;
}

export interface ReportFindingsInput {
  /**
   * Effort level the review ran at
   */
  level?: "low" | "medium" | "high" | "xhigh" | "max";
  /**
   * Verified findings, most-severe first; empty if none survived
   *
   * @maxItems 32
   */
  findings: {
    /**
     * Repo-relative path of the file the finding is in
     */
    file: string;
    /**
     * 1-indexed line the finding anchors to
     */
    line?: number;
    /**
     * One-sentence statement of the defect
     */
    summary: string;
    /**
     * Concrete inputs/state → wrong output/crash
     */
    failure_scenario: string;
    /**
     * Short kebab-case slug of the finding type, e.g. "correctness", "simplification", "efficiency", "test-coverage"
     */
    category?: string;
    /**
     * Set when a verify pass ran; absent on inline-only reviews
     */
    verdict?: "CONFIRMED" | "PLAUSIBLE";
    /**
     * Set ONLY when re-reporting after applying fixes: what happened to this finding
     */
    outcome?: "fixed" | "skipped" | "no_change_needed";
  }[];
}

export interface ScheduleWakeupInput {
  /**
   * Seconds from now to wake up. Clamped to [60, 3600] by the runtime. Required unless `stop` is true.
   */
  delaySeconds?: number;
  /**
   * One short sentence explaining the chosen delay. Goes to telemetry and is shown to the user. Be specific. Required unless `stop` is true.
   */
  reason?: string;
  /**
   * The /loop input to fire on wake-up. Pass the same /loop input verbatim each turn so the next firing re-enters the skill and continues the loop. For autonomous /loop (no user prompt), pass the literal sentinel `<<autonomous-loop-dynamic>>` instead (the dynamic-pacing variant, not the CronCreate-mode `<<autonomous-loop>>`). Required unless `stop` is true.
   */
  prompt?: string;
  /**
   * Set to true to end the dynamic loop immediately instead of scheduling another wakeup. When true, all other fields are ignored and no further wakeups fire.
   */
  stop?: boolean;
}

export interface SendMessageInput {
  /**
   * Recipient: teammate name
   */
  to: string;
  /**
   * A 5-10 word summary shown as a preview in the UI (required when message is a string)
   */
  summary?: string;
  /**
   * Plain text message content
   */
  message: string;
}

export interface SkillInput {
  /**
   * The name of a skill from the available-skills list. Do not guess names.
   */
  skill: string;
  /**
   * Optional arguments for the skill
   */
  args?: string;
}

export interface TaskCreateInput {
  /**
   * A brief title for the task
   */
  subject: string;
  /**
   * What needs to be done
   */
  description: string;
  /**
   * Present continuous form shown in spinner when in_progress (e.g., "Running tests")
   */
  activeForm?: string;
  /**
   * Arbitrary metadata to attach to the task
   */
  metadata?: {
    [k: string]: unknown;
  };
}

export interface TaskGetInput {
  /**
   * The ID of the task to retrieve
   */
  taskId: string;
}

export interface TaskListInput {}

export interface TaskOutputInput {
  /**
   * The task ID to get output from
   */
  task_id: string;
  /**
   * Whether to wait for completion
   */
  block: boolean;
  /**
   * Max wait time in ms
   */
  timeout: number;
}

export interface TaskStopInput {
  /**
   * The ID of the background task to stop. Agent-team teammates and named background agents are also accepted by agent ID or name.
   */
  task_id?: string;
  /**
   * Deprecated: use task_id instead
   */
  shell_id?: string;
}

export interface TaskUpdateInput {
  /**
   * The ID of the task to update
   */
  taskId: string;
  /**
   * New subject for the task
   */
  subject?: string;
  /**
   * New description for the task
   */
  description?: string;
  /**
   * Present continuous form shown in spinner when in_progress (e.g., "Running tests")
   */
  activeForm?: string;
  /**
   * New status for the task
   */
  status?: ("pending" | "in_progress" | "completed") | "deleted";
  /**
   * Task IDs that this task blocks
   */
  addBlocks?: string[];
  /**
   * Task IDs that block this task
   */
  addBlockedBy?: string[];
  /**
   * New owner for the task
   */
  owner?: string;
  /**
   * Metadata keys to merge into the task. Set a key to null to delete it.
   */
  metadata?: {
    [k: string]: unknown;
  };
}

export interface ToolSearchInput {
  /**
   * Query to find deferred tools. Use "select:<tool_name>" for direct selection, or keywords to search.
   */
  query: string;
  /**
   * Maximum number of results to return (default: 5)
   */
  max_results: number;
}

export interface WebFetchInput {
  /**
   * The URL to fetch content from
   */
  url: string;
  /**
   * The prompt to run on the fetched content
   */
  prompt: string;
}

export interface WebSearchInput {
  /**
   * The search query to use
   */
  query: string;
  /**
   * Only include search results from these domains
   */
  allowed_domains?: string[];
  /**
   * Never include search results from these domains
   */
  blocked_domains?: string[];
}

export interface WorkflowInput {
  /**
   * Self-contained workflow script. Must begin with `export const meta = { name, description, phases }` (pure literal, no computed values) followed by the script body using agent()/parallel()/pipeline()/phase().
   */
  script?: string;
  /**
   * Name of a predefined workflow (built-in or from .claude/workflows/). Resolves to a self-contained script.
   */
  name?: string;
  /**
   * Ignored — set the workflow description in the script's `meta` block.
   */
  description?: string;
  /**
   * Ignored — set the workflow title in the script's `meta` block.
   */
  title?: string;
  /**
   * Optional input value exposed to the script as the global `args`, verbatim. Pass arrays/objects as actual JSON values, NOT as a JSON-encoded string — a stringified list breaks `args.filter`/`args.map` in the script. Use for parameterized named workflows (e.g. a research question).
   */
  args?: {
    [k: string]: unknown;
  };
  /**
   * Path to a workflow script file on disk. Every Workflow invocation persists its script under the session directory and returns the path in the tool result. To iterate, edit that file with Write/Edit and re-invoke Workflow with the same `scriptPath` instead of re-sending the full script. Takes precedence over `script` and `name`.
   */
  scriptPath?: string;
  /**
   * Run ID of a prior Workflow invocation to resume from. Completed agent() calls with unchanged (prompt, opts) return their cached results instantly; only edited or new calls re-run. Same-session only. Stop the prior run first (TaskStop) before resuming.
   */
  resumeFromRunId?: string;
}

export interface WriteInput {
  /**
   * The absolute path to the file to write (must be absolute, not relative)
   */
  file_path: string;
  /**
   * The content to write to the file
   */
  content: string;
}

export type ToolName =
  | "Agent"
  | "Bash"
  | "CronCreate"
  | "CronDelete"
  | "CronList"
  | "DeferredToolPlaceholder"
  | "Edit"
  | "EnterWorktree"
  | "ExitWorktree"
  | "NotebookEdit"
  | "Read"
  | "ReportFindings"
  | "ScheduleWakeup"
  | "SendMessage"
  | "Skill"
  | "TaskCreate"
  | "TaskGet"
  | "TaskList"
  | "TaskOutput"
  | "TaskStop"
  | "TaskUpdate"
  | "ToolSearch"
  | "WebFetch"
  | "WebSearch"
  | "Workflow"
  | "Write";

export const TOOL_NAMES: readonly ToolName[] = [
  "Agent",
  "Bash",
  "CronCreate",
  "CronDelete",
  "CronList",
  "DeferredToolPlaceholder",
  "Edit",
  "EnterWorktree",
  "ExitWorktree",
  "NotebookEdit",
  "Read",
  "ReportFindings",
  "ScheduleWakeup",
  "SendMessage",
  "Skill",
  "TaskCreate",
  "TaskGet",
  "TaskList",
  "TaskOutput",
  "TaskStop",
  "TaskUpdate",
  "ToolSearch",
  "WebFetch",
  "WebSearch",
  "Workflow",
  "Write",
];

export interface ToolInputMap {
  Agent: AgentInput;
  Bash: BashInput;
  CronCreate: CronCreateInput;
  CronDelete: CronDeleteInput;
  CronList: CronListInput;
  DeferredToolPlaceholder: DeferredToolPlaceholderInput;
  Edit: EditInput;
  EnterWorktree: EnterWorktreeInput;
  ExitWorktree: ExitWorktreeInput;
  NotebookEdit: NotebookEditInput;
  Read: ReadInput;
  ReportFindings: ReportFindingsInput;
  ScheduleWakeup: ScheduleWakeupInput;
  SendMessage: SendMessageInput;
  Skill: SkillInput;
  TaskCreate: TaskCreateInput;
  TaskGet: TaskGetInput;
  TaskList: TaskListInput;
  TaskOutput: TaskOutputInput;
  TaskStop: TaskStopInput;
  TaskUpdate: TaskUpdateInput;
  ToolSearch: ToolSearchInput;
  WebFetch: WebFetchInput;
  WebSearch: WebSearchInput;
  Workflow: WorkflowInput;
  Write: WriteInput;
}
